version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: task_management_app
    volumes:
      - ./backend:/var/www
    networks:
      - task_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=task_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

  nginx:
    image: nginx:alpine
    container_name: task_management_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task_network

  db:
    image: mysql:8.0
    container_name: task_management_db
    environment:
      - MYSQL_DATABASE=task_db
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - task_network

  node:
    image: node:20-alpine
    container_name: task_management_node
    working_dir: /usr/src/app
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "if [ ! -f package.json ]; then npm init -y; fi && npm install && if [ -f 'package.json' ] && grep -q '\"dev\"' 'package.json'; then npm run dev; else tail -f /dev/null; fi"
    networks:
      - task_network

networks:
  task_network:
    driver: bridge

volumes:
  db_data:
